### ISSUE TITLE
Fail to install from Github

### ISSUE THREAD

**Issue by pqrXTN** [teazrq/RLT#1]
I guess there is a wrong print() function in ./Trees/Definition.h:59

error log:

Installing package into ‘/Users/tianning/Library/R/3.6/library’
(as ‘lib’ is unspecified)
* installing *source* package ‘RLT’ ...
** using staged installation
** libs
/usr/local/clang_llvm_9.0.0/bin/clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Users/tianning/Library/R/3.6/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/RcppArmadillo/include" -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/dqrng/include" -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/BH/include" -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/sitmo/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include -fopenmp -fPIC  -Wall -g -O2  -c ForestKernel.cpp -o ForestKernel.o
In file included from ForestKernel.cpp:8:
In file included from ./Trees/Trees.h:15:
./Trees/Definition.h:59:3: error: C++ requires a type specifier for all declarations
  print(){
  ^
1 error generated.
make: *** [ForestKernel.o] Error 1
ERROR: compilation failed for package ‘RLT’
* removing ‘/Users/tianning/Library/R/3.6/library/RLT’
Error: Failed to install 'RLT' from GitHub:
  (converted from warning) installation of package ‘/var/folders/9f/z8gdwxrs1pb4m5_jbcwtmwch0000gn/T//Rtmp8hXuBG/file4d34303c7c2a/RLT_4.0.0.tar.gz’ had non-zero exit status

**Comment by teazrq** [comment]
Yea, sorry for the late response. 
That was supposed to be a function that prints out the parameter settings. 
However, we haven't finished it. 
I commented it out, and hopefully, you can compile without a problem. 
The project is still on-going and there are a lot of features we are adding to this new package. 
So you might encounter errors over time. 
Thanks!
